import {render} from 'react-dom' // eslint-disable-line no-unused-vars
import Logo from './Logo.jsx'
import React from 'react'
import styled from 'styled-components'

const InnerWrapper = styled.div`
  max-width: 930px;
  margin-left: auto;
  margin-right: auto;
  padding-left: 15px;
  padding-right: 15px;  
`
const Link = styled.li`
  display: inline-block;

  & + & {
    margin-left: 20px;
  }
`
const Links = styled.ul`
  margin: 30px 0 0 0;
`
const LogoWrapper = styled.a`
  display: inline-block;
  color: #E8E8E8;
  margin-bottom: 20px;
`
const Wrapper = styled.footer`
  background-color: #E8E8E8;
  font-family: 'Roboto Condensed', 'Helvetica Neue', Arial, Helvetica, Geneva, sans-serif;
  font-size: 13px;
  margin-top: 80px;
  overflow: hidden;
  padding: 20px;
  text-align: center;

  a {
    color: #EA8C55;
    text-decoration: underline;
  }
`

export default class Footer extends React.Component {
  render () {
    return (
      <Wrapper>
        <InnerWrapper>
          <LogoWrapper href='https://speedtracker.org'>
            <Logo width={40} />
          </LogoWrapper>

          <p>Report generated by <a href='https://speedtracker.org'>SpeedTracker</a>. Data captured using <a href='https://www.webpagetest.org/'>WebPageTest</a>.</p>
          <p>SpeedTracker is an open-source project built by <a href='https://eduardoboucas.com'>Eduardo Bouças</a>. Logo design by <a href='https://thenounproject.com/elves.sousa/'>Elves Sousa</a>.</p>

          <Links>
            <Link>
              <a href='https://speedtracker.org'>Get your own</a>
            </Link>
            <Link>
              <a href='https://github.com/speedtracker'>Report an issue</a>
            </Link>
            <Link>
              <a href='https://twitter.com/speed_tracker'>Follow platform updates</a>
            </Link>
          </Links>
        </InnerWrapper>
      </Wrapper>
    )
  }
}
